version: '3.8'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.1
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - F:\Proyectos\20250819/producto-service/target/logs:/host-logs:ro
      - F:\Proyectos\20250819/orden-service/target/logs:/host-logs2:ro
      - F:\Proyectos\20250819/inventario-service/target/logs:/host-logs2:ro
    depends_on:
      - logstash
    mem_limit: 128m
    cpus: 0.25
    networks:
      - observability

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.1
    container_name: logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    mem_limit: 512m
    cpus: 0.25
    networks:
      - observability

networks:
  observability:
